import type { PageServerLoad } from './$types';
import { ucwords } from '$lib/php';
import { leagueName } from '$lib/site';
import formats from '../../../../static/data/gamemaster/formats.json';

/**
 * rankings.php. Every clean `/rankings/...` URL is rerouted here (lib/rewrites.ts), so
 * `get` already holds cup/cp/cat/p.
 *
 * PHP loaded `data/formats.php` — a PHP array generated by data/compile.php from
 * data/gamemaster/formats.json — purely to title cup rankings. We read the JSON source
 * directly instead (same data, same order).
 */
interface Format {
	title: string;
	cup: string;
	cp: number;
}

export const load: PageServerLoad = async ({ parent }) => {
	const { get } = await parent();

	// `get` values are already htmlspecialchars()'d by the root layout, exactly like the
	// PHP page escaped $_GET itself before header.php ran — do not escape a second time.
	const cp = get && get.cp !== undefined ? get.cp : '1500';
	const cup = get && get.cup !== undefined ? get.cup : 'all';

	let canonical = `/rankings/${cup}/${cp}/overall/`;

	// switch($cp) with an empty default branch
	let league = leagueName(cp, '');

	if (cup !== 'all') {
		// PHP compared `$cp == $format['cp']` (string vs int): a plain numeric-string match.
		const format = (formats as Format[]).find((f) => cup === f.cup && cp === String(f.cp));
		if (format) {
			league = format.title;
		}
	}

	let title = `${league} PvP Rankings`;
	let description = `Explore the top Pokemon for Pokemon GO PvP in the ${league}. Rankings include top moves, matchups, and counters for every Pokemon, as well as ratings for different roles.`;

	if (get && get.p !== undefined) {
		// ucwords(str_replace('_',' ', explode('-', htmlspecialchars($_GET['p']))[0]))
		let name = ucwords(get.p.split('-')[0].replace(/_/g, ' '));

		if (name === 'Lanturnw') {
			name = 'Lanturn';
		}

		title = `${name} ${league} PvP Rankings`;
		description = `Explore key matchups, moves, and counters for ${name} in ${league}.`;
		canonical = `/rankings/${cup}/${cp}/overall/${get.p}/`;
	}

	return { meta: { canonical, title, description } };
};
